[project]
name = "nicegui-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.1",
    "fastexcel>=0.16.0",
    "nicegui>=3.2.0",
    "polars>=1.35.1",
    "pyarrow>=22.0.0",
]
